name: wisemind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0
  just_audio: ^0.9.39
  audio_session: ^0.1.18
  cached_network_image: ^3.3.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # >>> добавлено для автоматической генерации адаптеров Hive
  build_runner: ^2.4.5
  hive_generator: ^2.0.1
  # <<< добавлено

flutter:
  uses-material-design: true

  assets:
    - assets/data/dbt_skills.json