name: wisemind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0
  just_audio: ^0.9.39
  audio_session: ^0.1.18
  cached_network_image: ^3.3.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  purchases_flutter: ^9.10.0
  purchases_ui_flutter: ^9.10.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  webview_flutter: ^4.13.0
  amplitude_flutter: ^4.3.9
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon/icon.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/icon/icon.png

  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^6.0.0

  # >>> добавлено для автоматической генерации адаптеров Hive
  build_runner: ^2.4.5
  hive_generator: ^2.0.1
  # <<< добавлено

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/skills/ru/
    - assets/images/skills/en/
    - assets/images/onboarding/
    - assets/images/usage_guide/en/
    - assets/images/usage_guide/ru/
    - assets/data/meditations-ru.json
    - assets/data/meditations-en.json
    - assets/data/skills_base.json
    - assets/data/skills_ru.json
    - assets/data/skills_en.json
    - assets/images/dbt_faq/ru/
    - assets/images/dbt_faq/en/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon/icon.png
  adaptive_icon_foreground: assets/images/icon/icon_foreground.png
  adaptive_icon_background: "#FFFFFF"